version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./data:/app/data
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "19006:19006"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://backend:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  uploads:
  vector_data:
